language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - npm run setup
  - npm run lint
  - npm test

after_success:
  - npm run coveralls
