---
name: "default name"
slug: "default"

# configuration variables for the server app
server:
  host: "http://127.0.0.1:8000"
  proxy_urls:
    password_change: "/api/v1/{org_slug}/account/password/change"
    password_reset: "/api/v1/{org_slug}/account/password/reset"
    password_reset_confirm: "/api/v1/{org_slug}/account/password/reset/confirm"
    registration: "/api/v1/{org_slug}/account"
    user_auth_token: "/api/v1/{org_slug}/account/token"
  secret_key: organization_secret_key
  timeout: 2 #request timeout period in seconds

# configuration variables for the client
# Path of all the assets should be defined relative to the organization's folder
# in assets directory.
client:
  # <title> value
  title: "Wifi Login"

  auto_login: True

  # path of favicon
  favicon: null

  # path of the custom css file relative to organization's folder in
  # assets directory.
  css_path: "index.css"
  languages:
    - text: "english"
      slug: "en"
  default_language: "en"
  components:
    header:
      logo:
        url: null # logo url
        alternate_text: null
      links:
        - text:
            en: "link-1" #link text in english
          url: "https://link-1.com"
        - text:
            en: "link-2"
          url: "https://link-2.com"

    footer:
      links:
        - text:
            en: "link-1"
          url: "https://link-1.com"
        - text:
            en: "link-2"
          url: "https://link-2.com"
      # secondary text to be displayed in smaller size in next line.
      # Eg. copyright text
      secondary_text:
        en: null

    registration_form:
      header:
        en: " sign up"
      input_fields:
        username:
          type: "text"
          pattern: '[a-zA-Z@.+\-_\d]{1,150}'
          pattern_description:
            en: "only letters, numbers, and @/./+/-/_ characters"
          placeholder:
            en: "enter phone number or username"
          label:
            en: "phone number or username"
        email:
          type: "email"
          pattern: null
          pattern_description:
            en: null
          placeholder:
            en: "email address"
          label:
            en: "email"
        password:
          type: "password"
          pattern: ".{6,}"
          pattern_description:
            en: "password must be a minimum of 6 characters"
          placeholder:
            en: "password"
          label:
            en: "password"
        password_confirm:
          type: "password"
          pattern: null
          pattern_description:
            en: null
          placeholder:
            en: "confirm password"
          label:
            en: "confirm"
      buttons:
        register:
          label: null
          text:
            en: "sign up"
      additional_info_text:
        en: "By signing up, you accept the {terms_and_conditions} and the {privacy_policy} of this WiFi service. "
      links:
        login:
          en: "Already have an account? Log in"

    reset_form:
      heading:
        en: "reset your password"
      additional_text:
        en: "enter your email and we'll send you the instructions to reset your password"
      input_fields:
        email:
          type: "email"
          pattern: null
          pattern_description:
            en: null
          placeholder:
            en: "email address"
          label:
            en: "email"
      buttons:
        send:
          en: 'send'
      login_page_link:
        text:
          en: "Take me Back to Sign In"

    confirm_form:
      heading:
        en: "reset your password"
      additional_text:
        en: "please enter your new password"
      input_fields:
        password:
          type: "password"
          pattern: ".{6,}"
          pattern_description:
            en: "password must be a minimum of 6 characters"
          placeholder:
            en: "password"
          label:
            en: "password"
        password_confirm:
          type: "password"
          pattern: null
          pattern_description:
            en: null
          placeholder:
            en: "confirm password"
          label:
            en: "confirm"
      buttons:
        submit:
          en: 'change password'

    login_form:
      header:
        en: " sign in"
      social_login:
        divider_text:
          en: "OR"
        description:
          en: "login with"
        links:
          -
            text: null
            url: null
            icon: null #relative to organization's folder in assets directory.
      input_fields:
        username:
          type: "text"
          pattern: '[a-zA-Z@.+\-_\d]{1,150}'
          pattern_description:
            en: "only letters, numbers, and @/./+/-/_ characters"
          placeholder:
            en: "enter username"
          label:
            en: "username"
        password:
          type: "password"
          pattern: ".{6,}"
          pattern_description:
            en: "password must be a minimum of 6 characters"
          placeholder:
            en: "password"
          label:
            en: "password"
      additional_info_text:
        en: "By logging in, you accept the {terms_and_conditions} and the {privacy_policy} of this WiFi service. "
      buttons:
        login:
          label: null
          text:
            en: "sign in"
      links:
        forget_password :
          en: "Forgot your password?"
        register:
          en: "Not registered yet? Create an account"
  privacy_policy:
    title:
      en: "privacy policy"
    content: null
  terms_and_conditions:
    title:
      en: "terms and conditions"
    content: null
