---
name: "default name"
slug: "default"

# configuration variables for the server app
server:
  host: "http://127.0.0.1:8000"
  proxy_urls:
    password_change: "/api/v1/{org_slug}/account/password/change"
    password_reset: "/api/v1/{org_slug}/account/password/reset"
    password_reset_confirm: "/api/v1/{org_slug}/account/password/reset/confirm"
    registration: "/api/v1/{org_slug}/account"
    user_auth_token: "/api/v1/{org_slug}/account/token"
  secret_key: organization_secret_key
  timeout: 2 #request timeout period in seconds

# configuration variables for the client
# Path of all the assets should be defined relative to the organization's folder
# in assets directory.
client:
  # <title> value
  title: "Wifi Login"

  # path of favicon
  favicon: null

  # path of the custom css file relative to organization's folder in
  # assets directory.
  css_path: null
  languages:
    - text: "english"
      slug: "en"
  default_language: "en"
  components:
    header:
      logo:
        url: null # logo url
        alternate_text: null
      links:
        - text:
            en: "link-1" #link text in english
          url: "https://link-1.com"
        - text:
            en: "link-2"
          url: "https://link-2.com"

    footer:
      links:
        - text:
            en: "link-1"
          url: "https://link-1.com"
        - text:
            en: "link-2"
          url: "https://link-2.com"
      # secondary text to be displayed in smaller size in next line.
      # Eg. copyright text
      secondary_text:
        en: null

    registration_form:
      header:
        en: " sign up"
      input_fields:
        username:
          type: "text"
          pattern: '[a-zA-Z@.+\-_]{1,150}'
          pattern_description:
            en: "only letters, numbers, and @/./+/-/_ characters"
          placeholder:
            en: "enter phone number or username"
          label:
            en: "phone number or username"
        email:
          type: "email"
          pattern: null
          pattern_description:
            en: null
          placeholder:
            en: "email address"
          label:
            en: "email"
        password:
          type: "password"
          pattern: ".{6,}"
          pattern_description:
            en: "password must be a minimum of 6 characters"
          placeholder:
            en: "password"
          label:
            en: "password"
        password_confirm:
          type: "password"
          pattern: null
          pattern_description:
            en: null
          placeholder:
            en: "confirm password"
          label:
            en: "confirm"
      buttons:
        register:
          en: 'sign up' # text for register button

    reset_form:
      heading:
        en: "reset your password"
      additional_text:
        en: "enter your email and we'll send you the instructions to reset your password"
      input_fields:
        email:
          type: "email"
          pattern: null
          pattern_description:
            en: null
          placeholder:
            en: "email address"
          label:
            en: "email"
      buttons:
        send:
          en: 'send'
      login_page_link:
        text:
          en: "Take me Back to Sign In"

    confirm_form:
      heading:
        en: "reset your password"
      additional_text:
        en: "please enter your new password"
      input_fields:
        password:
          type: "password"
          pattern: ".{6,}"
          pattern_description:
            en: "password must be a minimum of 6 characters"
          placeholder:
            en: "password"
          label:
            en: "password"
        password_confirm:
          type: "password"
          pattern: null
          pattern_description:
            en: null
          placeholder:
            en: "confirm password"
          label:
            en: "confirm"
      buttons:
        submit:
          en: 'change password'

    login_form:
      input_field:
        username:
          type: "text"
          placeholder:
            en: "Enter phone number or username"
          label:
            en: "Phone number or username" # default username field label
          pattern: null # pattern for validation
        password:
          type: "password"
          placeholder:
            en: "Enter password"
          label:
            en: "Password" # default password field
          pattern: null
      buttons:
        login:
          label:
            en: null # label field text for login button
          value:
            en: 'Login' # text for login button
        register:
          label:
            en: null # label field text for register button
          value:
            en: 'Sign up for free' # text for register button
      links:
        - forget_password :
            en: "Forgot your password?"
        - account:
            en: "Manage your account"
